
trigger:
- master

jobs:
- job: Build
  steps:
  - script: echo get thingies from dev?

- job: Test1
  dependsOn: Build
  steps:
  - script: echo run set 1 of tests

- job: Test2
  dependsOn: Build
  steps:
  - script: echo run set 2 of tests

- job: Test3
  dependsOn: Build
  steps:
  - script: exit 1 echo run set 3 of tests

- job: TestF
  dependsOn: Build
  steps:
  - script: exit 1

- job: Success
  dependsOn:
  - Test1
  - Test2
  - Test3
  - TestF
  condition: and(succeeded('Test1'),succeeded('Test2'),succeeded('Test3'))
  steps:
  - script: echo SUCCESS push thingies to test?

- job: Fail
  dependsOn:
  - Test1
  - Test2
  - Test3
  - TestF
  condition: or(failed('Test1'),failed('Test2'),failed('Test3'),failed('TestF'))
  steps:
    - script: echo FAIL send fail message and something
